CEPGP_EncounterInfo = {
	ID = {
		[1084] = "Onyxia",
		[785] = "High Priestess Jeklik",
		[784] = "High Priest Venoxis",
		[786] = "High Priestess Mar'li",
		[787] = "Bloodlord Mandokir",
		[788] = "Edge of Madness",
		[789] = "High Priest Thekal",
		[790] = "Gahz'ranka",
		[791] = "High Priestess Arlokk",
		[792] = "Jin'do the Hexxer",
		[793] = "Hakkar",
		[663] = "Lucifron",
		[664] = "Magmadar",
		[665] = "Gehennas",
		[666] = "Garr",
		[667] = "Shazzrah",
		[668] = "Baron Geddon",
		[669] = "Sulfuron Harbinger",
		[670] = "Golemagg the Incinerator",
		[671] = "Majordomo Executus",
		[672] = "Ragnaros",
		[610] = "Razorgore the Untamed",
		[611] = "Vaelastrasz the Corrupt",
		[612] = "Broodlord Lashlayer",
		[613] = "Firemaw",
		[614] = "Ebonroc",
		[615] = "Flamegor",
		[616] = "Chromaggus",
		[617] = "Nefarian",
		[718] = "Kurinnaxx",
		[719] = "General Rajaxx",
		[720] = "Moam",
		[721] = "Buru the Gorger",
		[722] = "Ayamiss the Hunter",
		[723] = "Ossirian the Unscarred",
		[709] = "The Prophet Skeram",
		[710] = "The Silithid Royalty",
		[711] = "Battleguard Sartura",
		[712] = "Fankriss the Unyielding",
		[713] = "Viscidus",
		[714] = "Princess Huhuran",
		[715] = "The Twin Emperors",
		[716] = "Ouro",
		[717] = "C'Thun",
		[1107] = "Anub'Rekhan",
		[1110] = "Grand Widow Faerlina",
		[1116] = "Maexxna",
		[1117] = "Noth the Plaguebringer",
		[1112] = "Heigan the Unclean",
		[1115] = "Loatheb",
		[1113] = "Instructor Razuvious",
		[1109] = "Gothik the Harvester",
		[1121] = "The Four Horsemen",
		[1118] = "Patchwerk",
		[1111] = "Grobbulus",
		[1108] = "Gluth",
		[1120] = "Thaddius",
		[1119] = "Sapphiron",
		[1114] = "Kel'Thuzad"
	},
	Bosses = {
		["Onyxia"] = 5,

		["Lucifron"] = 5,
		["Magmadar"] = 5,
		["Gehennas"] = 5,
		["Garr"] = 5,
		["Baron Geddon"] = 5,
		["Shazzrah"] = 5,
		["Sulfuron Harbinger"] = 5,
		["Golemagg the Incinerator"] = 5,
		["Majordomo Executus"] = 5,
		["Ragnaros"] = 7,

		["Razorgore the Untamed"] = 7,
		["Vaelastrasz the Corrupt"] = 7,
		["Broodlord Lashlayer"] = 7,
		["Firemaw"] = 7,
		["Ebonroc"] = 7,
		["Flamegor"] = 7,
		["Chromaggus"] = 7,
		["Nefarian"] = 10,

		["High Priest Venoxis"] = 2,
		["High Priestess Jeklik"] = 2,
		["High Priestess Mar'li"] = 2,
		["High Priest Thekal"] = 2,
		["High Priestess Arlokk"] = 2,
		["The Edge of Madness"] = 2,
		["Bloodlord Mandokir"] = 2,
		["Jin'do the Hexxer"] = 2,
		["Gahz'ranka"] = 2,
		["Hakkar"] = 3,

		["Kurinnaxx"] = 3,
		["General Rajaxx"] = 3,
		["Moam"] = 3,
		["Buru the Gorger"] = 3,
		["Ayamiss the Hunter"] = 3,
		["Ossirian the Unscarred"] = 4,

		["The Prophet Skeram"] = 10,
		["Battleguard Sartura"] = 10,
		["Fankriss the Unyielding"] = 10,
		["Princess Huhuran"] = 10,
		["The Silithid Royalty"] = 10,
		["Viscidus"] = 10,
		["Ouro"] = 10,
		["The Twin Emperors"] = 10,
		["C'Thun"] = 12,

		["Anub'Rekhan"] = 12,
		["Grand Widow Faerlina"] = 12,
		["Maexxna"] = 15,

		["Noth the Plaguebringer"] = 12,
		["Heigan the Unclean"] = 12,
		["Loatheb"] = 15,

		["Instructor Razuvious"] = 12,
		["Gothik the Harvester"] = 12,
		["The Four Horsemen"] = 15,

		["Patchwerk"] = 12,
		["Grobbulus"] = 12,
		["Gluth"] = 12,
		["Thaddius"] = 15,

		["Sapphiron"] = 15,
		["Kel'Thuzad"] = 15,

		["Doom Lord Kazzak"] = 7,
		["Azuregos"] = 7,
		["Emeriss"] = 7,
		["Lethon"] = 7,
		["Ysondre"] = 7,
		["Taerar"] = 7
	}
}
