FELWOODGATHER_FELWOODGATHER="FelwoodGather"
--descriptions
FELWOODGATHER_HELPMSG1="此插件只有在费伍德森林有效";
FELWOODGATHER_HELPMSG2="在费伍德森林，你可以在地图上看到费伍德森林的水果图标";
FELWOODGATHER_HELPMSG3="如果你有计时信息，那么计时器会自动显示 ";
FELWOODGATHER_HELPMSG4="水果下次刷新时间";
FELWOODGATHER_HELPMSG5="你可以使用/fwg share来分享你的计时信息";
--menu
FELWOODGATHER_CLEARTIMER="清除";
FELWOODGATHER_ANNOUNCE="通告";
FELWOODGATHER_SHARETIMER="共享所有计时";
FELWOODGATHER_MAPCONFIG="小地图设置";
FELWOODGATHER_LOCKWINDOW="锁定窗口";
--object information
FWG_WHIPPER_ROOT_TUBER="鞭根块茎";
FWG_NIGHT_DRAGON_BREATH="夜龙之息";
FWG_WINDBLOSSOM_BERRIES="风花果";
FWG_JADEFIRE_GLEN="碧火谷";
FWG_JADENAR="加德纳尔";
FWG_FALLS="血毒瀑布";
FWG_RIVER="血毒河";
FWG_GRAVEYARD="墓地";
FWG_JADEFIRE_RUN="碧火小径";
FWG_SHATTER_SCAR_VALE="碎痕谷";
FWG_EMERALD_SANCTUARY="翡翠圣地";
FWG_TALONBRANCH_GLADE="Talonbranch Grade";
FWG_IRONTREE_WOODS="铁木森林"
FWG_NORTH_FELWOOD="北费伍德森林";
FWG_WRT_TEXTURE="Interface\\Icons\\INV_Misc_Food_55";
FWG_NDB_TEXTURE="Interface\\Icons\\INV_Misc_Food_45";
FWG_WBB_TEXTURE="Interface\\Icons\\INV_Misc_Food_58";
-- slash command
FWG_SUBCOMMAND_SHARE="share";
FWG_SUBCOMMAND_CONFIG="config";
FWG_SUBCOMMAND_COUNT="count";
FWG_SUBCOMMAND_MAP="map";
FWG_SUBCOMMAND_RESET="reset";
FWG_SLASHHELPMSG1="此插件仅在费伍德森林有效 .";
FWG_SLASHHELPMSG2="/fwg share - 广播计时信息给队友";
FWG_SLASHHELPMSG3="/fwg config - 开启/关闭设置窗口";
FWG_SLASHHELPMSG4="/fwg count - 5秒拾取倒计时";
FWG_SLASHHELPMSG5="/fwg map - 开启/关闭水果小地图";
FWG_SLASHHELPMSG6="/fwg reset - 重置小地图窗口位置";
-- internal control
FWG_FELWOOD_MAPNAME="费伍德森林";
FWG_KALIMDOR_MAPNAME="卡利姆多";
FWG_LOOTMSG_MATCH_PATTERN="You receive item:(.+)%.";
-- share timer
FELWOODGATHER_SHARE_TIMER_FORMAT="%s %d %02d:%02d %s at %s(%d, %d)";
FELWOODGATHER_PARSE_FORMAT="([^%s]+) ([^%s]+) ([^%s]+):([^%s]+)";
--notification
FWG_NOTIFY_MESSAGE="%s - at %s 将在 %02d:%02d 后刷新！";
FWG_BROADCAST_COUNTS=" 个计时器 已广播.";
FWG_NOT_HAVE_TIMER="你没有任何计时信息";
--tooltip
FWG_TOOLTIP_TEXT="%s - %s\n %s";
FWG_NO_TIMER="";
--config window
FELWOODGATHER_OPTIONS="费伍德水果助手";
FWG_NOTIFY="提醒";
FELWOODGATHERMAP_TITLE="地图|cFF00FFFF(右键选项)";
FELWOODGATHERMAP_OPTIONS="地图设置";
FELWOODGATHER_OPTIONS_DONE="完成";
FELWOODGATHER_OPTIONS_TRANSPARENCY="透明度";
FELWOODGATHER_OPTIONS_SCALE="缩放";
FELWOODGATHER_OPTIONS_AUTOSHOW="自动显示";
FELWOODGATHER_OPTIONS_ACCEPTTIMER="接受计时";
FELWOODGATHER_OPTIONS_WARN1="第一次提醒";
FELWOODGATHER_OPTIONS_WARN2="第二次提醒";
FELWOODGATHER_OPTIONS_WARN_HIGH="25分钟";
FELWOODGATHER_OPTIONS_WARN_LOW="0分钟";
FELWOODGATHER_OPTIONS_MINUTE="分钟";
FELWOODGATHER_OPTIONS_ICONSIZE="图标大小";
--cooldown
FELWOODGATHER_OPENNOW="打开";
FELWOODGATHER_PICKUP="拾取";
--bindings
BINDING_HEADER_FELWOODGATHER=FELWOODGATHER_FELWOODGATHER;
BINDING_NAME_FELWOODGATHER_TOGGLE_CONFIG_WINDOW="开启/关闭设置窗口";
BINDING_NAME_FELWOODGATHER_COUNTDOWN="Countdown Call";
--class text
FWG_WARRIOR="战士";
FWG_ROGUE="盗贼";
FWG_HUNTER="猎人";
FWG_MAGE="法师";
FWG_WARLOCK="术士";
FWG_DRUID="德鲁伊";
FWG_PRIEST="牧师";
FWG_SHAMAN="萨满祭司";
FWG_PALADIN="圣骑士";
FELWOODGATHER_ONLY_IN_FELWOOD="小地图只会在费伍德森林显示.";