Guidelime.registerGuide(
[[
[GA Horde]
[N41-43 Part]
[NX43-45 Part]
[D This guide was written by TUGs and is totally free, but if you want to support my work use: https://www.youtube.com/user/HydroxXTV]
This guide was written by TUGs and is totally free, but if you want to support my work use: https://www.youtube.com/user/HydroxXTV
I am leaving out EVERY Elite quest and most dungeons in this guide. especially on release YOU SHOULD NOT!!! You'll easily find groups for elite quests and dungeons. Do them as often as you can and at least once for their quests!
Do: [QC782]
TurnIn: [QT1108]
TurnIn: [QT703]
Accept: [QA1137]
TurnIn: [QT711]
Accept: [QA712]
TurnIn: [QT1419]
TurnIn: [QT782]
TurnIn: [QT2258]
Grind in at the rock elemental areas till level [XP42 42]
Use your [H] Hearthstone.
Buy your missing Stranglethorn Pages as well as *Frost Oil*,*Gyrochronatom* and *Patterned Bronze Bracers* from the AH. For the Items: IN THIS ORDER AS WELL, If you cant get Item 1->Dont buy item 2 and 3, they rely on each other as pre quests.
Take the Zeppelin to Stranglethorn Valley
Fly to [F Stonard]
TurnIn: [QT1420]
Accept: [QA430]
Do: [QC699]
TurnIn: [QT699]
Accept: [QA1422]
TurnIn: [QT1422]
Accept: [QA1426]
Do: [QC1426]
TurnIn: [QT1426]
Accept: [QA1427]
TurnIn: [QT1427]
Accept: [QA1728]
Do: [QC1428]
Do: [QC1430]
TurnIn: [QT1428]
TurnIn: [QT1430]
Fly to [F Kargath]
Do: [QC712]
TurnIn: [QT712]
Accept: [QA713]
TurnIn: [QT713]
Accept: [QA714]
TurnIn: [QT714]
Accept: [QA734]
Accept: [QA716]
TurnIn: [QT716]
]], "TUGs The Ultimate (Leveling) Guides")